linters:
  enable:
    - revive
linters-settings:
  revive:
    ignore-generated-header: true
    severity: error
    rules:
      - name: exported
      - name: unexported-naming
      - name: unexported-return
      - name: package-comments
      - name: var-naming
issues:
  exclude-use-default: false