version: "2"
linters:
  enable:
    - revive
  settings:
    revive:
      severity: error
      rules:
        - name: exported
        - name: unexported-naming
        - name: unexported-return
        - name: package-comments
        - name: var-naming
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
